name: Release

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run build

      - name: Run tests
        run: bun run test --run

      # Temporary workaround until bun publish supports OIDC publishing
      - name: Rewrite workspace dependencies
        run: |
          # Get version from package.json
          VERSION=$(cat packages/core/package.json | bunx json version)

          # Fix workspace dependency in fs package
          cd packages/fs
          bunx json -I -f package.json -e "this.dependencies['@modern-tar/core']='$VERSION'"

      - name: Pack packages
        run: |
          cd packages/core
          bun pm pack

          cd ../fs
          bun pm pack

      - name: Publish packages
        run: |
          # Publish core package first
          cd packages/core
          TARBALL=$(ls *.tgz | head -n 1)
          bunx npm publish "$TARBALL"

          # Publish fs package
          cd ../fs
          TARBALL=$(ls *.tgz | head -n 1)
          bunx npm publish "$TARBALL"
